### ISSUE TITLE
Project Stage 2 Checklist

### ISSUE THREAD

**Issue by LinearJester** [aleksanderwlodarczyk/tpum#3]
- [x] text is in C# and use .NET
- [x] build succeeded
- [x] all UT are green
- [ ] layers are clearly stated using language terms only
- [ ] `Data` API is abstract and contains object model representing process data, must be clearly stated
- [ ] prove that the data integration is implemented.
- [ ] `Logic` uses only the abstract `Data` layer API
- [x] Communication between the client and the server should be made using the `Web Socket`
- [ ] reactive and interactive communication are used
- [ ] client API must be clearly stated
- [ ] Unit Test - layers are tested independently using abstract API
- [ ] Dependency injection (additional framework is not required)
- [ ] Mock is used for testing purpose (expected but not required)
