### ISSUE TITLE
Project Stage 3 Checklist

### ISSUE THREAD

**Issue by LinearJester** [aleksanderwlodarczyk/tpum#4]
- [x] program jest w .NET
- [x] program się kompiluje
- [ ] testy jednostkowe na zielono
- [ ] można utworzyć jednocześnie dwie instancje programu (dwa procesy)
- [ ] instancje serwera i klienta współdziałają (test integracyjny)
- [ ] Oba programy maja wymagane warstwy Prezentacja, Logika, Dane
- [ ] Programy komunikują się z wykorzystaniem WebSocket
- [ ] Wykorzystano współdziałanie interaktywne
- [ ] Wykorzystano współdziałanie reaktywne (samorzutne/subskrypcja) z wykorzystaniem mechanizmu subskrypcji zrealizowanej poprzez implementację IObservable
- [ ] Wykorzystano serializacji z wykorzystaniem jednej ze składni `JSON`, `YAML`, `XML`
- [ ] wydzielono sekcję krytyczną i zabezpieczono w niej spójność danych
- [ ] Oba programy korzystają ze wspólnego modelu obiektowego
- [x] Opracowano model wymiany danych z wykorzystaniem OPC UA
- [ ] Harmonizacja modeli - wygenerowano ekwiwalentny model i porównano go z napisanym ręcznie
